# Generated by Django 5.2.6 on 2026-08-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('chat_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, default='', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние бота',
                'verbose_name_plural': 'Состояния бота',
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=16)),
                ('message_type', models.CharField(default='text', max_length=16)),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.business')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-timestamp'],
            },
        ),
    ]
