# Generated by Django 5.2.6 on 2026-08-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('coffee', 'Кофейня'), ('bakery', 'Пекарня'), ('minimarket', 'Мини-маркет'), ('restaurant', 'Ресторан'), ('pharmacy', 'Аптека'), ('flower', 'Цветочный')], max_length=30)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('logo_emoji', models.CharField(default='🏪', max_length=8)),
                ('allow_surplus_sharing', models.BooleanField(default=True)),
                ('favorite_tools', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бизнес',
                'verbose_name_plural': 'Бизнесы',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'ordering': ['id'],
            },
        ),
    ]
