# Generated by Django 5.2.6 on 2026-08-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='📦', max_length=8)),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('min_order', models.IntegerField(default=0)),
                ('avg_delivery_hours', models.IntegerField(default=24)),
                ('reliability_score', models.IntegerField(default=100)),
                ('total_orders', models.IntegerField(default=0)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('short_deliveries', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🧰', max_length=8)),
                ('category', models.CharField(choices=[('warehouse', 'Склад'), ('purchasing', 'Закупки'), ('suppliers', 'Поставщики'), ('analytics', 'Аналитика'), ('notifications', 'Уведомления')], max_length=30)),
                ('route', models.CharField(max_length=100)),
                ('recommended_for', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=16)),
                ('min_stock', models.FloatField()),
                ('avg_daily_usage', models.FloatField()),
                ('shelf_life_days', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.supplier')),
            ],
            options={
                'verbose_name': 'Цена поставщика',
                'verbose_name_plural': 'Цены поставщиков',
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
