# Generated by Django 5.2.6 on 2026-08-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevented_stockouts', models.IntegerField(default=0)),
                ('saved_from_writeoff', models.IntegerField(default=0)),
                ('group_purchase_savings', models.IntegerField(default=0)),
                ('reduced_frozen_capital', models.IntegerField(default=0)),
                ('on_time_delivery_rate', models.IntegerField(default=100)),
                ('avg_deficit_resolution_hours', models.FloatField(default=0)),
                ('automated_operations', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Метрики ценности',
                'verbose_name_plural': 'Метрики ценности',
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('receipt', 'Приход'), ('sale', 'Продажа'), ('writeoff', 'Списание'), ('transfer_in', 'Приём'), ('transfer_out', 'Передача'), ('adjustment', 'Корректировка')], max_length=20)),
                ('quantity', models.FloatField()),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('manual', 'Вручную'), ('auto_order', 'Автозаказ'), ('rescue', 'Резерв')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Событие склада',
                'verbose_name_plural': 'События склада',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('preparing', 'Собирается'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('issue', 'Проблема')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('auto_order', 'Автозаказ'), ('wave', 'Волна'), ('tender', 'Тендер')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplier')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='supply.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price_per_unit', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseWave',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('collecting', 'Сбор'), ('ready', 'Готова'), ('ordered', 'Заказана'), ('delivered', 'Доставлена'), ('cancelled', 'Отменена')], default='collecting', max_length=20)),
                ('target_quantity', models.FloatField()),
                ('individual_price', models.IntegerField()),
                ('group_price', models.IntegerField()),
                ('savings_per_unit', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Закупочная волна',
                'verbose_name_plural': 'Закупочные волны',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply.purchasewave'),
        ),
        migrations.CreateModel(
            name='RescueTransfer',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('distance_km', models.FloatField(default=0)),
                ('price_per_unit', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Предложено'), ('accepted', 'Принято'), ('completed', 'Завершено'), ('declined', 'Отклонено')], default='proposed', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_offers', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('to_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_requests', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Соседский резерв',
                'verbose_name_plural': 'Соседские резервы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('current_stock', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ok', 'В норме'), ('low', 'Мало'), ('critical', 'Критично'), ('surplus', 'Излишек')], default='ok', max_length=16)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='WaveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('confirmed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='supply.purchasewave')),
            ],
            options={
                'unique_together': {('wave', 'business')},
            },
        ),
    ]
